openapi: 3.1.0
info:
  title: super-seisan
  description: ""
  version: 1.0.0
tags: []
paths:
  /seisan/{seisanId}/currencies:
    post:
      summary: Add Currency
      deprecated: false
      description: 通貨を追加
      operationId: addCurrencyToSeisan
      tags: []
      parameters:
        - name: seisanId
          in: path
          description: 紐づける精算のID
          required: true
          example: ""
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CurrencyInput"
            examples: {}
        required: true
      responses:
        "200":
          description: 成功時
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Seisan"
          headers: {}
      security: []
  /seisan/{seisanId}/currencies/{id}:
    put:
      summary: Update Currency
      deprecated: false
      description: 通貨を更新
      operationId: updateCurrencyInSeisan
      tags: []
      parameters:
        - name: seisanId
          in: path
          description: 紐づく精算のID
          required: true
          example: ""
          schema:
            type: string
        - name: id
          in: path
          description: 更新する通貨のID
          required: true
          example: ""
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CurrencyInput"
            examples: {}
        required: true
      responses:
        "200":
          description: 成功時
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Seisan"
          headers: {}
      security: []
    delete:
      summary: Remove Currency
      deprecated: false
      description: 通貨を削除
      operationId: removeCurrencyFromSeisan
      tags: []
      parameters:
        - name: seisanId
          in: path
          description: 紐づく精算のID
          required: true
          example: ""
          schema:
            type: string
        - name: id
          in: path
          description: 通貨のID
          required: true
          example: ""
          schema:
            type: string
      responses:
        "200":
          description: 成功時
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Seisan"
          headers: {}
      security: []
  /seisan/{seisanId}/participants:
    post:
      summary: Add Participant
      deprecated: false
      description: 参加者を追加
      operationId: addParticipantToSeisan
      tags: []
      parameters:
        - name: seisanId
          in: path
          description: 紐づける精算のID
          required: true
          example: ""
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ParticipantInput"
            examples: {}
        required: true
      responses:
        "200":
          description: 成功時
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Seisan"
          headers: {}
      security: []
  /seisan/{seisanId}/participants/{id}:
    put:
      summary: Update Participant
      deprecated: false
      description: 参加者を更新
      operationId: updateParticipantInSeisan
      tags: []
      parameters:
        - name: seisanId
          in: path
          description: 紐づく精算のID
          required: true
          example: ""
          schema:
            type: string
        - name: id
          in: path
          description: 参加者のID
          required: true
          example: ""
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ParticipantInput"
            examples: {}
        required: true
      responses:
        "200":
          description: 成功時
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Seisan"
          headers: {}
      security: []
    delete:
      summary: Remove Participant
      deprecated: false
      description: 参加者を削除
      operationId: removeParticipantFromSeisan
      tags: []
      parameters:
        - name: seisanId
          in: path
          description: 紐づく精算のID
          required: true
          example: ""
          schema:
            type: string
        - name: id
          in: path
          description: 参加者のID
          required: true
          example: ""
          schema:
            type: string
      responses:
        "200":
          description: 成功時
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Seisan"
          headers: {}
      security: []
  /seisan/{seisanId}/items:
    post:
      summary: Add Item
      deprecated: false
      description: 項目を追加
      operationId: addItemToSeisan
      tags: []
      parameters:
        - name: seisanId
          in: path
          description: 紐づける精算のID
          required: true
          example: ""
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ItemInput"
            examples: {}
        required: true
      responses:
        "200":
          description: 成功時
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Seisan"
          headers: {}
      security: []
  /seisan/{seisanId}/items/{id}:
    put:
      summary: Update Item
      deprecated: false
      description: 項目を更新
      operationId: updateItemInSeisan
      tags: []
      parameters:
        - name: seisanId
          in: path
          description: 紐づく精算のID
          required: true
          example: ""
          schema:
            type: string
        - name: id
          in: path
          description: 項目のID
          required: true
          example: ""
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ItemInput"
            examples: {}
        required: true
      responses:
        "200":
          description: 成功時
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Seisan"
          headers: {}
        "409":
          description: 編集衝突時
          content:
            application/json:
              schema:
                type: object
                properties:
                  current:
                    $ref: "#/components/schemas/Item"
                    description: 項目
                  incoming:
                    $ref: "#/components/schemas/Item"
                    description: 項目
                required:
                  - current
                  - incoming
              example:
                current:
                  id: 03fe8970-affc-44b5-9fa7-034be6aaa937
                  name: モロヘイヤと鴨肉のパイ
                  icon: ♠️
                  payer:
                    id: 57738884-0c1c-4472-8333-f32c891d87ef
                    name: 武35
                    icon: 🎾
                    createdAt: "2026-01-21T15:05:38.352Z"
                    updatedAt: "2026-01-21T15:05:38.352Z"
                  price: 188.15
                  currency:
                    id: a0d79935-2024-4224-8670-86925c026d09
                    code: ジブラルタルポンド
                    rate: 566.09
                    createdAt: "2026-01-21T15:05:38.352Z"
                    updatedAt: "2026-01-21T15:05:38.352Z"
                  amount: 7
                  total: 659.75
                  exempts:
                    - id: 3be97f07-f8be-4537-9aa8-41714ac5407d
                      name: 蓮.小林94
                      icon: 🤏🏿
                      createdAt: "2026-01-21T15:05:38.353Z"
                      updatedAt: "2026-01-21T15:05:38.353Z"
                    - id: f72476ff-dee3-48f9-b01b-074b40ff837c
                      name: 静子67
                      icon: 🐐
                      createdAt: "2026-01-21T15:05:38.353Z"
                      updatedAt: "2026-01-21T15:05:38.354Z"
                  version: "8304860782890431"
                  createdAt: "2026-01-21T15:05:38.354Z"
                  updatedAt: "2026-01-21T15:05:38.354Z"
                incoming:
                  id: 4c8e7210-d33a-4623-a888-53e11112fa15
                  name: 照り焼きチキン
                  icon: 🙇🏿
                  payer:
                    id: e234be33-487d-404e-b1ac-439c2046982b
                    name: 正子.山本
                    icon: 🙅🏽‍♂️
                    createdAt: "2026-01-21T15:05:38.354Z"
                    updatedAt: "2026-01-21T15:05:38.354Z"
                  price: 912.05
                  currency:
                    id: da136d09-3a87-4def-ac71-6c9928b994fa
                    code: トリニダード・トバゴドル
                    rate: 777.69
                    createdAt: "2026-01-21T15:05:38.354Z"
                    updatedAt: "2026-01-21T15:05:38.354Z"
                  amount: 3
                  total: 72
                  exempts:
                    - id: 5f1119fc-51e1-4959-a807-88c65c823088
                      name: 湊.山本86
                      icon: 🐼
                      createdAt: "2026-01-21T15:05:38.355Z"
                      updatedAt: "2026-01-21T15:05:38.355Z"
                    - id: 8848ddde-27a1-4794-9fb7-56665ef0c71a
                      name: 朝陽.松本
                      icon: 😕
                      createdAt: "2026-01-21T15:05:38.355Z"
                      updatedAt: "2026-01-21T15:05:38.355Z"
                    - id: 85513dff-0c1f-44e5-acab-bb60095eec62
                      name: 大雅.中村77
                      icon: 🌅
                      createdAt: "2026-01-21T15:05:38.355Z"
                      updatedAt: "2026-01-21T15:05:38.355Z"
                  version: "6136408544774357"
                  createdAt: "2026-01-21T15:05:38.355Z"
                  updatedAt: "2026-01-21T15:05:38.355Z"
          headers: {}
      security: []
    delete:
      summary: Remove Item
      deprecated: false
      description: 項目を削除
      operationId: removeItemFromSeisan
      tags: []
      parameters:
        - name: seisanId
          in: path
          description: 紐づく精算のID
          required: true
          example: ""
          schema:
            type: string
        - name: id
          in: path
          description: 項目のID
          required: true
          example: ""
          schema:
            type: string
      responses:
        "200":
          description: 成功時
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Seisan"
          headers: {}
      security: []
  /seisan:
    post:
      summary: Add Seisan
      deprecated: false
      description: 精算を作成
      operationId: addSeisan
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SeisanInput"
            examples: {}
        required: true
      responses:
        "200":
          description: 成功時
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Seisan"
          headers: {}
      security: []
  /seisan/{id}:
    put:
      summary: Update Seisan
      deprecated: false
      description: 精算を更新
      operationId: updateSeisan
      tags: []
      parameters:
        - name: id
          in: path
          description: 精算のID
          required: true
          example: ""
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SeisanInput"
            examples: {}
        required: true
      responses:
        "200":
          description: 成功時
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Seisan"
          headers: {}
      security: []
    get:
      summary: Get Seisan
      deprecated: false
      description: 精算を取得
      operationId: getSeisanById
      tags: []
      parameters:
        - name: id
          in: path
          description: 精算のID
          required: true
          example: ""
          schema:
            type: string
      responses:
        "200":
          description: 成功時
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Seisan"
          headers: {}
      security: []
webhooks: {}
components:
  schemas:
    SeisanResultDetailItem:
      type: object
      properties:
        id:
          type: string
          description: ID
        source:
          $ref: "#/components/schemas/Item"
          description: 項目
        subtotal:
          type: number
          description: 小計
      required:
        - id
        - source
        - subtotal
    SeisanResultDetail:
      type: object
      properties:
        id:
          type: string
          description: ID
        participant:
          $ref: "#/components/schemas/Participant"
          description: 参加者
        total:
          type: number
          description: 合計
        paid:
          type: number
          description: 支払い済額
        difference:
          type: number
          description: 差額
        items:
          type: array
          items:
            $ref: "#/components/schemas/SeisanResultDetailItem"
      required:
        - id
        - participant
        - total
        - paid
        - difference
        - items
    SeisanResult:
      type: object
      properties:
        id:
          type: string
          description: ID
        surplus:
          type: number
          description: 余り
        details:
          type: array
          items:
            $ref: "#/components/schemas/SeisanResultDetail"
          description: 参加者ごとの詳細
      required:
        - id
        - surplus
        - details
    Currency:
      type: object
      properties:
        id:
          type: string
          description: ID
        code:
          type: string
          description: 通貨名
        rate:
          type: number
          description: 対円レート
        createdAt:
          type: string
          description: 作成日時
        updatedAt:
          type: string
          description: 更新日時
      required:
        - id
        - code
        - rate
        - createdAt
        - updatedAt
    Participant:
      type: object
      properties:
        id:
          type: string
          description: ID
        name:
          type: string
          description: 名前
        icon:
          type: string
          description: アイコン
        createdAt:
          type: string
          description: 作成日時
        updatedAt:
          type: string
          description: 更新日時
      required:
        - id
        - name
        - icon
        - createdAt
        - updatedAt
    Item:
      type: object
      properties:
        id:
          type: string
          description: ID
        name:
          type: string
          description: 名前
        icon:
          type: string
          description: アイコン
        payer:
          $ref: "#/components/schemas/Participant"
          description: 参加者
        price:
          type: number
          description: 単価
        currency:
          anyOf:
            - $ref: "#/components/schemas/Currency"
            - type: "null"
          description: 通貨
        amount:
          type: integer
          description: 個数
        total:
          type: number
          description: 小計
        exempts:
          type: array
          items:
            $ref: "#/components/schemas/Participant"
            description: 参加者
          description: 割り勘から除外する参加者
        version:
          type: integer
          description: バージョン
        createdAt:
          type: string
          description: 作成日時
        updatedAt:
          type: string
          description: 更新日時
      required:
        - id
        - name
        - icon
        - payer
        - price
        - amount
        - total
        - exempts
        - version
        - createdAt
        - updatedAt
    Seisan:
      type: object
      properties:
        id:
          type: string
          description: ID
        name:
          type: string
          description: 名前
        icon:
          type: string
          description: アイコン
        items:
          type: array
          items:
            $ref: "#/components/schemas/Item"
            description: 項目
          description: 精算項目
        participants:
          type: array
          items:
            $ref: "#/components/schemas/Participant"
            description: 参加者
          description: 参加者
        currencies:
          type: array
          items:
            $ref: "#/components/schemas/Currency"
          description: 通貨
        result:
          $ref: "#/components/schemas/SeisanResult"
          description: 精算結果
        createdAt:
          type: string
          description: 作成日時
        updatedAt:
          type: string
          description: 更新日時
      required:
        - id
        - name
        - icon
        - items
        - participants
        - currencies
        - result
        - createdAt
        - updatedAt
    SeisanInput:
      type: object
      properties:
        name:
          type: string
          title: 名前
        emoji:
          type: string
          title: アイコン
      required:
        - name
        - emoji
    ItemInput:
      type: object
      properties:
        name:
          type: string
          description: 名前
        icon:
          type: string
          description: アイコン
        payerId:
          type: string
          description: 支払い者のID
        price:
          type: number
          description: 単価
        currencyId:
          type:
            - string
            - "null"
          description: 通貨ID
        amount:
          type: integer
          description: 個数
        total:
          type: number
          description: 小計
        exemptIds:
          type: array
          items:
            type: string
          description: 割り勘から除外する参加者
        version:
          type: integer
          description: バージョン
      required:
        - name
        - icon
        - payerId
        - price
        - amount
        - total
        - exemptIds
        - version
    CurrencyInput:
      type: object
      properties:
        code:
          type: string
          description: 通貨名
        rate:
          type: number
          description: 対円レート
      required:
        - code
        - rate
    ParticipantInput:
      type: object
      properties:
        name:
          type: string
          description: 名前
        icon:
          type: string
          description: アイコン
      required:
        - name
        - icon
  securitySchemes: {}
servers: []
