syntax = "proto3";

package super_seisan;

message Transactions {
  string item = 0 [(required) = true];
  string buyer = 1 [(required) = true];
  double price = 2 [(required) = true];
  uint32 quantity = 3 [(required) = true];
  repeated string exemptions = 4;
  string currency_symbol = 5;
}

message Currency {
  string symbol = 0 [(required) = true];
  double rate = 1 [(required) = true];
}

message Payload {
  repeated Transactions transactions = 0;
  repeated string users = 1;
  repeated Currency currencies = 2;
}
