name: CI - Legacy

on:
  push:
    paths:
      - .github/workflows/ci-legacy.yml
      - legacy/**
      - superseisan.proto

defaults:
  run:
    working-directory: legacy

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@08c4be7e2e672a47d11bd04269e27e5f3e8529cb # v6.0.0
        with:
          package_json_file: ./legacy/package.json

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: latest
          cache: pnpm
          cache-dependency-path: legacy

      - name: Install dependencies
        run: pnpm i

      - name: Generate codes
        run: pnpm run generate

      - name: Check formatting
        run: pnpm run lint

      - name: Check types
        run: pnpm run type-check

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@08c4be7e2e672a47d11bd04269e27e5f3e8529cb # v6.0.0
        with:
          package_json_file: ./legacy/package.json

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: latest
          cache: pnpm
          cache-dependency-path: legacy

      - name: Install dependencies
        run: pnpm i

      - name: Generate codes
        run: pnpm run generate

      - name: Run build
        run: pnpm run build
