name: CI - Legacy

on:
  push:
    paths:
      - .github/workflows/ci-legacy.yml
      - legacy/**
      - superseisan.proto

defaults:
  run:
    working-directory: legacy

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          package_json_file: ./legacy/package.json

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: latest
          cache: pnpm
          cache-dependency-path: legacy

      - name: Install dependencies
        run: pnpm i

      - name: Generate codes
        run: pnpm run generate

      - name: Check formatting
        run: pnpm run lint

      - name: Check types
        run: pnpm run type-check

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          package_json_file: ./legacy/package.json

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: latest
          cache: pnpm
          cache-dependency-path: legacy

      - name: Install dependencies
        run: pnpm i

      - name: Generate codes
        run: pnpm run generate

      - name: Run build
        run: pnpm run build
